### ISSUE TITLE
Allow multiple choices for filters

### ISSUE THREAD

**Issue by Atemu** [Benzhaomin/bdiefinder#10]
Currently you can only select one filter in each category (all other filters disappear after you select it), but many times I want to filter for multiple speeds and/or latencies.

**Comment by Benzhaomin** [comment]
I really like the drill-down filters we have now and I'd like to keep the basic use-case as simple as it is.

Maybe it'd be better to just fork the repo and host another version with the same data but a different UI.

**Comment by Benzhaomin** [comment]
As said above, I like the UI as it is and it can easily be forked
