### ISSUE TITLE
Add A-Die and M-Die support

### ISSUE THREAD

**Issue by rcmaehl** [Benzhaomin/bdiefinder#17]
Per Samsung. B-Die is now dead in favor of newer kits:
https://www.samsung.com/semiconductor/global.semi/file/resource/2018/06/DDR4_Product_guide_May.18.pdf

https://www.techpowerup.com/255165/samsung-kills-production-of-famed-b-die-ddr4-memory-in-favor-or-higher-densities

**Comment by Benzhaomin** [comment]
Need to look into Hynix and Micron stuff too once Ryzen 3000 reviews are out.

Good sources of info on them:

- https://www.hardwareluxx.de/community/f13/hynix-8gbit-ddr4-cjr-c-die-h5an8g8ncjr-1206340.html
- https://www.hardwareluxx.de/community/f13/micron-8gbit-e-die-ddr4-1233479.html

**Comment by Benzhaomin** [comment]
Turns out B-Die is still alive and kicking. Reopen this issue and/or start A/M-Die Finder first and then think about merging projects into a single x-Die Finder down the line.
