### ISSUE TITLE
Reporting non-B die SKU

### ISSUE THREAD

**Issue by alvgalrus** [Benzhaomin/bdiefinder#21]
Hello.

I've found a G.Skill TridentZ Neo F4-3600C16D-32GTZN which isn't a B die, its latencies are 16-19-19-39. It's a SK Hynix D-die. The webpage said it was _guaranteed_ to be Samsung B-die.

Could you add a way to report non-B dies?

Regards,
Álvaro

**Comment by Benzhaomin** [comment]
Hi, thanks for your comment. The best way to report errors is exactly what you did.

To help further you could submit a PR with the offending kit removed from `src/js/data.js`.

https://github.com/Benzhaomin/bdiefinder/blob/master/src/js/data.js#L516

You can also alert the guys at hardwareluxx.de, all data used here comes from them. 

https://www.hardwareluxx.de/community/threads/die-ultimative-hardwareluxx-samsung-8gb-b-die-liste-alle-hersteller-26-01-20.1161530/

**Comment by theosinitsin** [comment]
I just received the 16GB version of this (F4-3600C16D-16GTZN) and it's also not a B-die. Going to open a new issue for it.

**Comment by ashakoor** [comment]
the GTZN kits are Samsung, GTZNC kits are Hynix

**Comment by Chippi** [comment]
F4-3600C16D-32GTZN CL16-16-16-36 are Samsung b-die however.

**Comment by Salt-E-buck** [comment]
> I just received the 16GB version of this (F4-3600C16D-16GTZN) and it's also not a B-die. Going to open a new issue for it.

How did you gather (F4-3600C16D-32GTZN) is not B-die? Thaiphoon Burner shows that it is [
![image](https://user-images.githubusercontent.com/77212439/104109692-afe6d200-5324-11eb-84e0-04c729fb7b64.png)
](url)
