### ISSUE TITLE
G.Skill F4-3600C16D-16GTZN is not B-die

### ISSUE THREAD

**Issue by theosinitsin** [Benzhaomin/bdiefinder#26]
According to Thaiphoon Burner:

![image](https://user-images.githubusercontent.com/25334539/79378390-19f75580-7f12-11ea-919d-cf5700d6eaa0.png)

It's actually Hynix D-die.

**Comment by theosinitsin** [comment]
Disregard. The F4-3600C16D-16GTZN is B-die, but the F4-3600C16D-16GTZN**C** (what I got) is not. The C at the end makes all the difference.

**Comment by Benzhaomin** [comment]
Thank you for contributing anyway
