### ISSUE TITLE
New kit with B-die, but may be not exclusive?

### ISSUE THREAD

**Issue by grumd** [Benzhaomin/bdiefinder#31]
Bought G.Skill Ripjaws V 4000MHz 18-22-22-42 2x8Gb twice.
One was made in January 2020, Hynix DJR.
One was made in August 2020, Samsung B-die.
Confirmed by both Thaiphoon and by the codes on these sticks.

Do I make a PR for this stick, or is it too early to say that this stick is now B-die?

**Comment by Benzhaomin** [comment]
I prefer to stay cautious and only add guaranteed kits. Old inventory might still be in circulation in various countries and others might end-up with the kit you got in January as well. They are both great kits though.
