### ISSUE TITLE
Please add 4400Mhz CL16 options

### ISSUE THREAD

**Issue by T0m0rr0w** [Benzhaomin/bdiefinder#33]
Currently 4400 only lists CL17 or slower.
G.Skill now has CL16 versions available and considering the speed/latency i doubt these could be anything but B-Die.

https://www.gskill.com/products/1/165/Desktop-Memory
https://www.techpowerup.com/272590/g-skill-pushes-latency-down-with-new-ddr4-4000-cl16-ddr4-4400-cl16-memory-kits

**Comment by Benzhaomin** [comment]
Added, thanks for your help
