### ISSUE TITLE
Update links to portuguese stores

### ISSUE THREAD

**Issue by RavingSombra** [Benzhaomin/bdiefinder#39]
Heya
It's been a while since the creation of this project and today I realized the links to the stores need to be updated, as their websites were updated or don't exist anymore.

Here's the list with the updated formats (I'm using F4-3200C14D-16GTRS as reference):

- PCDiga (website update): https://www.pcdiga.com/#/embedded/query=F4-3200C14D-16GTRS&page=1&query_name=match_and
- Globaldata (website update): https://globaldata.pt/?query=F4-3200C14D-16GTRS
- Chiptec (unchanged): https://www.chiptec.net/catalogsearch/result/?cat=0&q=F4-3200C14D-16GTRS
- Alientech (went bankrupt, remove)
- Novo Atalho (unchanged): https://www.novoatalho.pt/pt-PT/pesquisa.html?txton=products&txtsearch=F4-3200C14D-16GTRS

**Comment by Benzhaomin** [comment]
thanks for your help
