### ISSUE TITLE
Search/Filter by product sku/model #

### ISSUE THREAD

**Issue by RuubixO** [Benzhaomin/bdiefinder#8]
Hello again,
My apologies for the spamming today! I think adding a way to put in a given sku or product number to confirm it's b-die would also be a great feature to add into this tool.

**Comment by Benzhaomin** [comment]
Very good idea. It can be done once I've added a lot more kits based on research done at [hardwareluxx.de](https://www.hardwareluxx.de/community/f13/die-ultimative-hardwareluxx-samsung-8gb-b-die-liste-alle-hersteller-07-05-18-a-1161530.html)

**Comment by Atemu** [comment]
You can achieve this by removing all filters and then searching for the product number through you browser's "Find in page".
